apiVersion: v1
kind: Pod
metadata:
  name: raspi1
spec:
  hostNetwork: true
  nodeSelector:
    kubernetes.io/hostname: node2
  containers:
  - name: my-container
    image: my-pod1-app
    securityContext:
      privileged: true
