apiVersion: v1
kind: Pod
metadata:
  name: my-pod2-app
spec:
  hostNetwork: true
  nodeSelector:
    kubernetes.io/hostname: node2
  containers:
  - name: my-container
    image: my-pod2-app
    securityContext:
      privileged: true
