apiVersion: v1
kind: Pod
metadata:
  name: raspi2
spec:
  hostNetwork: true
  nodeSelector:
    kubernetes.io/hostname: node3
  containers:
  - name: my-container
    image: my-pod2-app
    securityContext:
      privileged: true
